### ISSUE TITLE
Query about links on the House Legislative Data and Transparency Conference page

### ISSUE THREAD

**Issue by knowtheory** [usgpo/innovation#1]
Hey there!  Nerding out hard over here, and i was poking around the Innovation Hub site.

I noticed that there is [a page for an interesting conference from 2018](https://usgpo.github.io/innovation/events/2018-07-12-LDTC/)!

There's a bullet point for Slides that still says "coming soon", and i was wondering if any material on that front was available.  Additionally [the link to the agenda](https://cha.house.gov/sites/republicans.cha.house.gov/files/documents/committee_docs/Agenda_FINAL.pdf) has unfortunately gone dead.

Just thought I'd drop a line and mention those!

**Comment by llaplant** [comment]
@knowtheory fixed agenda link and replaced slides coming soon with video. Thanks!!!
