### ISSUE TITLE
CREC Senate 7/26/2023 — missing text pages at the end

### ISSUE THREAD

**Issue by TimTCM** [usgpo/innovation#17]
Your version of the [Senate Record for 7/26/2023](https://www.govinfo.gov/app/collection/crec/2023/07/07-26/4/SENATE) is missing pages at the end. They show in the PDF for the Entire Section and are missing from your text version list.

**Comment by TimTCM** [comment]
Looks good. Thank you!

**Comment by G2cme** [comment]
#13
